---

- name: Create installer directory
  file: state=directory path={{ mw_installer_folder }} owner={{ oracle_user }} group={{ oracle_group }}

- name: Copy oraInst.loc for silent installation
  template: src=oraInst.loc.j2 dest="{{ mw_installer_folder }}/oraInst.loc" owner={{ oracle_user }} group={{ oracle_group }}

- include: layout.yml
  vars:
    oracle_install_code: "{{ item }}"
  with_items: "{{ oracle_installs }}"

- name: cleanup
  file: path="{{ mw_installer_folder }}/oraInst.loc" state=absent
