---
# tasks file for staylorx.wlssoftware

- name: Create installer directory
  file: state=directory path={{ mw_installer_folder }} owner={{ oracle_user_name }} group={{ oracle_group_name }}
  become: yes
  become_user: "{{ oracle_user_name }}"

- name: Copy Middleware Installer
  copy: src=files/{{ mw_installer_name }} dest="{{ mw_installer_folder }}" owner={{ oracle_user_name }} group={{ oracle_group_name }}
  become_user: "{{ oracle_user_name }}"

- name: Copy file for silent installation
  template: src=silent-weblogic.txt.j2 dest="{{ mw_installer_folder }}/silent-weblogic.txt" owner={{ oracle_user_name }} group={{ oracle_group_name }}
  become_user: "{{ oracle_user_name }}"

- name: Copy OraInst.loc
  template: src=oraInst.loc.j2 dest="{{ mw_installer_folder }}/oraInst.loc" owner={{ oracle_user_name }} group={{ oracle_group_name }}
  become_user: "{{ oracle_user_name }}"

- name: execute Weblogic installer
  command: "{{ java_home }}/bin/java -Djava.security.egd=file:/dev/./urandom -Xmx1024m -jar {{ mw_installer_folder }}/{{ mw_installer_name }} -silent -responseFile {{ mw_installer_folder }}/silent-weblogic.txt -invPtrLoc {{ mw_installer_folder }}/oraInst.loc"
  args:
    creates: "{{ mw_home }}/"
  become_user: "{{ oracle_user_name }}"

- name: copy over the create-admin.py script
  template: src=templates/create-admin.py.j2 dest="{{ mw_installer_folder }}/create-admin.py" mode=0700

- name: check for domain home already installed
  stat: path="{{ domain_home }}"
  register: domain_home_var

# Not happy to have to do this but I need the urandom to increase the speed of this thing
- name: replace the wlst.sh script
  template: src=templates/wlst.sh.j2 dest="{{ mw_home }}/oracle_common/common/bin/wlst.sh" mode=0750

# Important. If the urandom file isn't passed to java this step can take 15+ minutes.
- name: create admin/domain
  command: "{{ mw_home }}/oracle_common/common/bin/wlst.sh {{ mw_installer_folder }}/create-admin.py"

- name: create the security folder for boot.properties
  file: path="{{ domain_home }}/servers/AdminServer/security" state=directory mode=0750
  become_user: "{{ oracle_user_name }}"

- name: copy over the boot.properties file
  template: src=templates/boot.properties.j2 dest="{{ domain_home }}/servers/AdminServer/security/boot.properties" mode=0660
  become_user: "{{ oracle_user_name }}"
